
%%  Step by Step Description of the Main file is given Below
% 1. This is the Main file to perform montage simulation Using ROAST
% 2. Then It will Perform AC-PC detection
% 3. iSATA  Electric Field Distribution will be provided for each AAL-116 ROIs
% 4. Dose Target Determination Index (DTDI) of the target areas will be provided
% Step 1-4 are from previous i-SATA MNI Version
%% Step 5 -ISATA Network Analysis Starts Here- 
% Electric Field intensity received by each network (AAL-116 atlas is divided into 9 Networks)
% Average Current Intensity for each Network- is shown as (NwCD)
% The Dose Network target engagement (DNTE)- Provides an index of the current
% intensity received by each network (in both hemispheres, and each
% hemisphere) Please refer to (Hu et al., 2024)
% Created By - Tanushree L Date -12 March, 2026- at NIMHANS, Bangalore
% tanushreelogukavi@gmail.com
% The code is distributed for the academic Purposes only


%% STEP 1 - ROAST Individual Script 
% Purpose: This script automates the simulation of electric fields in the
% brain using ROAST for individual subject MRI.

% --- DIRECT PATH CONFIGURATION ---
% Manually set your SATA and ROAST installation folders here
% for example
SATA_PATH  = '\Downloads\SATA'; 
ROAST_PATH = '\Downloads\SATA\roast-3.0'; %Updated ROAST version can also be used

% Add them to the MATLAB search path so the functions can be found
addpath(genpath(SATA_PATH));
addpath(genpath(ROAST_PATH));

global SATA_PATH ROAST_PATH;
SATA_CBL_init;

% --- 1. USER INPUT ---
mri_input_file  = '\sample_path\sub01_T1w\roast\Sub01_T1w.nii'; 
output_base_dir = '\sample_path\iSATA_results';

% --- 2. DOSE SETTINGS ---
electrode_loc1   = 'CP5';     
anode_current    = 2;         
electrode_loc2   = 'Cz';      
cathode_current  = -2;        
electrode_type   = 'pad';     
electrode_size   = [50 50 3]; 
cap_type         = '1005';

% --- 3. DIRECTORY PREPARATION ---
[input_folder, sub_name, ~] = fileparts(mri_input_file);
subject_roast_dir = fullfile(output_base_dir, sub_name, 'roast');

if ~exist(subject_roast_dir, 'dir')
    mkdir(subject_roast_dir);
end

fprintf('Starting Individual Processing for: %s\n', sub_name);

% --- 4. EXECUTE ROAST ---
% ROAST typically outputs files in the same directory as the input MRI file.
original_folder = pwd; 
try
    cd(ROAST_PATH);
    % Note: 'resampling' 'on' ensures 1mm isotropic voxels, which is good for FieldTrip
    roast(mri_input_file, {electrode_loc1, anode_current, electrode_loc2, cathode_current}, ...
        'electype', electrode_type, 'elecsize', electrode_size, 'captype', cap_type, 'resampling', 'on');
    
    % --- SAVE FIGURES ---
    all_figs = findobj('Type', 'figure');
    if ~isempty(all_figs)
        % Save as a MATLAB fig file (re-openable)
        fig_save_path = fullfile(subject_roast_dir, [sub_name, '_all_plots.fig']);
        savefig(all_figs, fig_save_path);
        
        % Export the main 3D view as a PNG
        saveas(all_figs(1), fullfile(subject_roast_dir, [sub_name, '_3D_Render.png']));
        
        fprintf('Figures saved to: %s\n', subject_roast_dir);
        close(all_figs); 
    end
catch ME
    warning('ROAST failed: %s', ME.message);
    cd(original_folder); 
    return;
end
cd(original_folder);

% --- 5. SELECTIVE MOVE & CLEANUP ---
% Move all files generated by ROAST from the input folder to the output folder
generated_files = dir(fullfile(input_folder, ['*', sub_name, '*']));
for j = 1:length(generated_files)
    source = fullfile(generated_files(j).folder, generated_files(j).name);
    destination = fullfile(subject_roast_dir, generated_files(j).name);
    
    % Move the file if it doesn't already exist at destination (or force move)
    if ~strcmp(source, destination)
        movefile(source, destination, 'f');
    end
end

% --- 6. FIELDTRIP REWRITE ---
% Search for the resampled/processed NIfTI to standardize for FieldTrip
% Define folder path
folder_path = '\sample_path\iSATA_results\Sub01_T1w\roast';

% Initialize output file variable
file_out = '';

% Look for '*1mm.nii' file
directoryIn = dir(fullfile(folder_path, '*1mm.nii'));
if numel(directoryIn) == 1
    file_out = SATA_CBL_FT_Rewrite(directoryIn.folder, directoryIn.name);
else
    % Look for '*RAS.nii' file
    directoryIn = dir(fullfile(folder_path, '*RAS.nii'));
    if numel(directoryIn) == 1
        file_out = SATA_CBL_FT_Rewrite(directoryIn.folder, directoryIn.name);
    else
        % Look for '*ras.nii' file
        directoryIn = dir(fullfile(folder_path, '*ras.nii'));
        if numel(directoryIn) == 1
            file_out = SATA_CBL_FT_Rewrite(directoryIn.folder, directoryIn.name);
        else
            % If no matching file is found, take any available NIfTI file
            directoryIn = dir(fullfile(folder_path, '*.nii'));
            if ~isempty(directoryIn)
                % Use the first found NIfTI file
                file_out = SATA_CBL_FT_Rewrite(directoryIn(1).folder, directoryIn(1).name);
            else
                error('No suitable NIfTI file found in the folder.');
            end
        end
    end
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% STEP - 2 Starts here to get acpc file run this commands in terminal 
export ARTHOME=/mnt/Downloads/SATA/Utilities/ART %set ART folder path from your SATA toolbox
export PATH=$ARTHOME/bin:$PATH
acpcdetect -i /mnt/sample_path/iSATA_Results/Sub01_T1w/roast/ftOut.nii%set path to your input roast file ftout.nii
%Note - run sudo apt install liblapack3 in wsl/ubuntu terminal to avoid
%error in installation 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Step 2 can be skipped by mannualy detecting ac-pc points from the brain image  
in_path  = 'D:\sample_path\iSATA_results\Sub01_T1w\roast'; 
txt_filepath = fullfile(in_path, 'ftOut_ACPC.txt');
[AC, PC] = SATA_acpc_extract(txt_filepath);

% 2. Save the result
if ~isempty(AC) && ~isempty(PC)
    save(fullfile(in_path, 'ACPC_coordinates.mat'), 'AC', 'PC');
    fprintf('Success: ACPC_coordinates.mat created in %s\n', in_path);
else
    warning('AC or PC coordinates were not found in the text file.');
end
%% STEP 3,4 &5 are combined in below script: ISATA Complete Network Analysis
% ========================================================================
% PURPOSE: 
%   To calculate how much electric current engages specific Brain area
%   The ranking of current intensity according to target selection
% Amount of current density received by each network - 9 networks are there
% The networks are also divided into left and right hemispheres
%% network Names "Default Mode", "Frontoparietal", "Dorsal Attention", 
% "Ventral Attention", "Sensorimotor", "Visual", "Limbic", 
% "Basal Ganglia", "Cerebellum" Please refer to  (Hu et al., 2024)
%
% SATA_CBL_Coords_With_High_MCD_MNI_atlas: Maps E-field to AAL atlas regions.
%
% INPUTS:
%   Montage   - Structure containing:
%               .Target.FaceVertexCData (E-field values)
%               .Target.Vertices (Mesh coordinates)
%               .ISATA (AC, PC, and MSP coordinates) [cite: 2026-03-21]
%               .sub_id (Subject identifier string)
%   atlas_nii - Path to the AAL atlas NIfTI file (.nii).
%   atlas_mat - Path to the AAL atlas label list (.mat).
%   out_dir   - Path to the directory where results and plots will be saved.
%
% OUTPUTS:
%   MNI_table - Table of Gyrus names and Average Current Density in 
%                    original atlas order.
%   DTDI_table     - Table of regions ranked by normalized DTDI values.
%   Files          - Saves '[sub_id]_MNI.mat', '[sub_id]_DTDI.mat', and 
%                    '[sub_id]_MNI_DTDI.png' to the output directory. 
% NwCD - Network current density of all networks
%Figure 1 will show NwCD for 9 networks, each hemisphere (L/R) and combined
%hemispheres (L&R together)
% DNTE- Will give the rank of current density received by networks
%Figure 2 will show DNTE for 9 networks, each hemisphere (L/R) and combined
%hemispheres (L&R together)

% =========================================================================

clear; clc;
% --- CONFIG ---
sub_id    = 'Sub01'; 
in_path   = '\Sample_path\Sub01\roast';  
out_path  = '\Sample_Data\Sub01\isata'; 

% FIX: Use single quotes to ensure this is a character array for SPM
atlas_nii = '\Downloads\SATA\Utilities\aal_for_SPM12\aal_for_SPM12\ROI_MNI_V4.nii';
atlas_mat = '\Downloads\SATA\Utilities\aal_for_SPM12\aal_for_SPM12\ROI_MNI_V4_List.mat';

if ~exist(out_path, 'dir'); mkdir(out_path); end

% --- BUILD MONTAGE ---
acpc_file = fullfile(in_path, 'ACPC_coordinates.mat');
if exist(acpc_file, 'file'); load(acpc_file); else; error('ACPC file not found!'); end

% ROBUST FILE SEARCH - Prevents "Search term must be text" error
mat_files = dir(fullfile(in_path, '*.mat'));
found_sim = false;
for i = 1:length(mat_files)
    curr_file = mat_files(i).name;
    % Ensure we are checking a valid string
    if ~isempty(curr_file) && contains(string(curr_file), 'T') && ~contains(string(curr_file), 'ACPC')
        load(fullfile(in_path, curr_file));
        found_sim = true;
        break;
    end
end

if ~found_sim; error('Could not find the simulation T-pattern file!'); end


% --- DATA RETRIEVAL ---
e_pos_list = dir(fullfile(in_path, '*e.pos'));
if isempty(e_pos_list); error('No .pos file found!'); end

% Load ROAST node/elem if not already in workspace
% load(fullfile(in_path, 'your_roast_output.mat')); 

% --- AUTOMATED MESH FILE SEARCH ---
% Search for all .mat files in the directory
mat_files = dir(fullfile(in_path, '*.mat'));
mesh_file = '';

% Pattern: SubjectID followed by underscore, 8 digits, 'T', and 6 digits
% Example: Sub01_20260330T124209.mat
pattern = [sub_id, '_\d{8}T\d{6}\.mat$'];

for i = 1:length(mat_files)
    if ~isempty(regexp(mat_files(i).name, pattern, 'once'))
        mesh_file = fullfile(in_path, mat_files(i).name);
        break; 
    end
end

if isempty(mesh_file)
    error('Could not find the primary ROAST mesh file for subject %s in %s', sub_id, in_path);
else
    fprintf('Found Mesh File: %s\n', mesh_file);
    load(mesh_file, 'node', 'elem');
end

% --- DATA RETRIEVAL ---
[Coordinates, Electric_Field] = SATA_CBL_Retrieve_Coords(e_pos_list(1), node, elem); 

% ---  MSP DETECTION (Step 3) ---
% You must detect the MSP before building the montage 
MSP = SATA_CBL_Detect_MSP(Coordinates, AC, PC); 

% ---  MONTAGE CONSTRUCTION ---
ISATA_Montage = struct();
ISATA_Montage.sub_id = sub_id; 
ISATA_Montage.Target.FaceVertexCData = Electric_Field; 
ISATA_Montage.Target.Vertices = Coordinates;
ISATA_Montage.ISATA.AC = AC; % [cite: 161]
ISATA_Montage.ISATA.PC = PC; % [cite: 162]
ISATA_Montage.ISATA.MSP = MSP; % [cite: 163]


% ---  RUN MAPPING (Step 4) ---

[mni_table, dtdi_table] = SATA_CBL_Coords_With_High_MCD_MNI_atlas(ISATA_Montage, atlas_nii, atlas_mat, out_path);

% Save Step 4 Plots as .fig in output directory
set(findobj('Name', 'i-SATA AAL 116 Results'), 'Visible', 'on');
savefig(gcf, fullfile(out_path, [sub_id '_MNI_DTDI.fig']));

% ---  NETWORK ANALYSIS (Step 5) ---
network_path = '\Downloads\SATA\Utilities\aal_for_SPM12\aal_for_SPM12\aal_MNI_V4_Network.mat';

if exist('mni_table', 'var') && ~isempty(mni_table)
    
    [dnte_m, dnte_d] = iSATA_MNI_Network(mni_table, network_path, sub_id, out_path);
    
    % 2. Save the resulting data tables to .mat files
    save(fullfile(out_path, [sub_id '_NwCD.mat']), 'dnte_m');
    save(fullfile(out_path, [sub_id '_DNTE.mat']), 'dnte_d');
    
    fprintf('Network Analysis Complete. Figures and Tables saved to: %s\n', out_path);
else
    warning('mni_table not found. Skipping Network Analysis.');
end
